# Generated by Django 5.1.5 on 2025-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.IntegerField(choices=[(1, 'Registro Civil'), (2, 'Tarjeta de Identidad'), (3, 'Cedula de Ciudadania'), (4, 'Tarjeta de Extranjería'), (5, 'Cedula de Extranjeria'), (6, 'NIT'), (7, 'Pasaporte'), (8, 'Documento de identificación extranjero'), (9, 'PEP'), (10, 'NIT otro país'), (11, 'NUIP*')], default=3)),
                ('document_number', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('names', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('p_type', models.IntegerField(choices=[(1, 'Persona Jurídica'), (2, 'Persona Natural')], default=2)),
                ('municipal', models.IntegerField()),
            ],
        ),
    ]
