# Generated by Django 5.1.5 on 2025-01-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='tribute',
            field=models.IntegerField(choices=[(1, 'IVA'), (2, 'No aplica')], default=1),
        ),
    ]
